name: Build CI

# Trigger the workflow on push
on: [push]

jobs:
  job1:
    name: Android Builds & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Base Setup
        run: npm run ci.base.setup

      - name: Lint
        run: npm run ci.tslint

      - name: Build Vanilla Android Demo App
        run: npm run ci.vanilla.android.build

      - name: Build Angular Android
        run: npm run ci.ng.android.build

      - name: Build Vue Android
        run: npm run ci.vue.android.build

      - name: Android Test
        run: |
          echo no | android create avd --force -n test -b armeabi-v7a
          emulator -avd test -no-audio -no-window &
          android-wait-for-emulator
          cd src && npm i && npm run tsc && cd ../demo && tns build android
          tns test android --justlaunch

  job2:
    name: iOS Builds & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Base Setup
        run: npm run ci.base.setup && npm run ci.pip.install

      - name: Build Vanilla iOS Demo App
        run: cd src && npm run ci.vanilla.ios.build

      - name: Build Angular iOS
        run: cd src && npm run ci.ng.ios.build

      - name: Build Vue iOS
        run: cd src && npm run ci.vue.ios.build

      - name: iOS Test
        run: |
          cd src && npm i && npm run tsc && cd ../demo && tns build ios
          tns test ios --justlaunch
